{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "suppline.fullname" . }}
  labels:
    {{- include "suppline.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "suppline.fullname" . }}
  labels:
    {{- include "suppline.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "suppline.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "suppline.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
