{{- if and .Values.registry.enabled .Values.registry.secrets.haSharedSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suppline.fullname" . }}-registry-secret
  labels:
    {{- include "suppline.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
type: Opaque
data:
  haSharedSecret: {{ .Values.registry.secrets.haSharedSecret | b64enc }}
{{- end }}
