{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    {{- include "suppline.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - port: {{ .Values.registry.service.port }}
      targetPort: registry
      protocol: TCP
      name: registry
  selector:
    {{- include "suppline.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: registry
{{- end }}
