apiVersion: v1
kind: Service
metadata:
  name: {{ include "suppline.fullname" . }}
  labels:
    {{- include "suppline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - name: api
    port: {{ .Values.backend.service.port }}
    targetPort: api
    protocol: TCP
  - name: metrics
    port: {{ .Values.backend.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
  - name: health
    port: {{ .Values.backend.service.healthPort }}
    targetPort: health
    protocol: TCP
  selector:
    {{- include "suppline.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "suppline.fullname" . }}-metrics
  labels:
    {{- include "suppline.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.backend.service.metricsPort | quote }}
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.backend.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "suppline.selectorLabels" . | nindent 4 }}
