{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suppline.fullname" . }}-ui-config
  labels:
    {{- include "suppline.frontend.labels" . | nindent 4 }}
data:
  API_BASE_URL: {{ .Values.frontend.apiBaseURL | quote }}
{{- end }}
